config/routes.rb
BurningAirline::Application.routes.draw do
  get "home/index"
  devise_for :users

  root :to => 'flights#landing'
  resources :airplanes
  resources :flights
  resources :reservations
  resources :seats
end

app/models/flight.rb
# == Schema Information
#
# Table name: flights
#
#  id          :integer          not null, primary key
#  flight_no   :string(255)
#  origin      :string(255)
#  destination :string(255)
#  date        :string(255)
#  airplane_id :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class Flight < ActiveRecord::Base
    attr_accessible :flight_no, :origin, :destination, :date, :airplane_id

    has_many :reservations
    belongs_to :airplane
    has_many :users, through: :reservations
    has_many :seats
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: [:show, :edit, :update, :destroy]

  before_filter :check_if_logged_in, :except => [:landing]


  def landing
  end

  # GET /flights
  # GET /flights.json
  def index
    @flights = Flight.all

    respond_to do |format|
      format.html 
      format.json { render json: @flights, :include => [:airplane, :reservations, :users, :seats] }
    end
  end

  # GET /flights/1
  # GET /flights/1.json
  def show
    @flights = Flight.find(params[:id])
    
    respond_to do |format|
      format.html 
      format.json { render json: @flights, :include => :airplane} 
    end
  end

  # GET /flights/new
  def new
    @flight = Flight.new
  end

  # GET /flights/1/edit
  def edit
  end

  # POST /flights
  # POST /flights.json
  def create
    @flight = Flight.new(flight_params)

    respond_to do |format|
      if @flight.save
        format.html { redirect_to @flight, notice: 'Flight was successfully created.' }
        format.json { render action: 'show', status: :created, location: @flight }
      else
        format.html { render action: 'new' }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end

    airplane = Airplane.find(@flight.airplane_id)

    rows_array = (1..airplane.row.to_i).to_a
    column_array = (1..airplane.column.to_i).to_a
    

    rows_array.each do |row_name|
      column_array.each do |column_name|
        seat_name = row_name.to_s + "-" + column_name.to_s 
        seat = Seat.create(:column_row => seat_name, :flight_id => @flight.id, :available => true)
      end
    end

  end

  # PATCH/PUT /flights/1
  # PATCH/PUT /flights/1.json
  def update
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to @flight, notice: 'Flight was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1
  # DELETE /flights/1.json
  def destroy
    @flight.destroy
    respond_to do |format|
      format.html { redirect_to flights_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight
      @flight = Flight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flight_params
      params.require(:flight).permit(:flight_no, :origin, :destination, :date, :airplane_id)
    end

    def check_if_logged_in
      redirect_to(root_path) if current_user.nil?
    end
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/flights/_form.html.erb
<%= form_for(@flight) do |f| %>
  <% if @flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
      <% @flight.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :flight_no %><br>
    <%= f.text_field :flight_no, :class => 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :origin %><br>
    <%= f.text_field :origin, :class => 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :destination %><br>
    <%= f.text_field :destination, :class => 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date, :class => 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :airplane_id %><br>
    <%= f.select :airplane_id, Airplane.all.map {|airplane| [airplane.name, airplane.id]}, :include_blank => true, :class => 'form-control' %>
  </div>
  <div class="actions">
    <br><%= f.submit "Create flight", :class => 'btn btn-success' %>
  </div>
<% end %>

app/views/flights/edit.html.erb
<h1>Editing flight</h1>

<%= render 'form' %>

<%= link_to 'Show', @flight %> |
<%= link_to 'Back', flights_path %>

app/views/flights/index.html.erb
<h1>Listing flights</h1>

<table>
  <thead>
    <tr>
      <th>Flight no</th>
      <th>Origin</th>
      <th>Destination</th>
      <th>Date</th>
      <th>Airplane</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @flights.each do |flight| %>
      <tr>
        <td><%= flight.flight_no %></td>
        <td><%= flight.origin %></td>
        <td><%= flight.destination %></td>
        <td><%= flight.date %></td>
        <td><%= flight.airplane_id %></td>
        <td><%= link_to 'Show', flight %></td>
        <td><%= link_to 'Edit', edit_flight_path(flight) %></td>
        <td><%= link_to 'Destroy', flight, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Flight', new_flight_path %>

app/views/flights/landing.html.erb
<div id="search">
</div>

<div id="main">
</div>
<% if !user_signed_in? %>
  <h2 class="text-center">Keep Calm!</h2>
  <h2 class="text-center">You're now in the safest airline in the world.</h2>
  <h2 class="text-center">Please sign in/sign up to use this service.</h2>
<% end %>

<script id="appView" type="text/x-underscore-template">
  <!-- The title All flights will be hidden at first, it will be displayed only after a user makes a search -->
  <h1 class="flights_title">All Flights  <i class="glyphicon glyphicon-plane"></i><i class="glyphicon glyphicon-plane"></i></h1>
  <ul id="flights"></ul>

  <!-- form to make a search -->
  <form>
    <h1 class="burning">Search flights  <i class="glyphicon glyphicon-plane"></i></h1>
    <input id="origin" class="form-control" placeholder="From">
    <input id="destination" class="form-control" placeholder="To">
    <br><button class="grow btn btn-success">Search</button>
  </form>
  <br>
</script>

<script id="flightListView" type="text/x-underscore-template">
  <div><a href="#flights/{{ id }}">From: {{origin}}, To: {{destination}}, Flight Reference: {{ flight_no }}, Date: {{date}}, Airplane id:  {{airplane_id}}, flight id: {{id}} </a></div>
</script>

 <script id="flightView" type="text/x-underscore-template">
  <div class="flight">
    <div class="content">
      <p><strong>Flight reference number:</strong> {{ flight_no }}</p>
      <p><strong>From: </strong> {{ origin }}</p>
      <p><strong>To:</strong> {{ destination }}</p>
      <p><strong>Date: </strong> {{ date }}</p>
      <p><strong>Airplane id:</strong> {{ airplane_id }}</p>
      <p><strong>Number of seats: </strong> {{ seatCount }}</p>
      <button class="grow btn btn-success">Book flight</button>
      <button class="grow btn btn-info"><a href='#'>Back</a></button>
    </div>
    <hr>
    <div id="seats">
    </div>
  </div>
</script>

<script id='seatsView' type="text/x-underscore-template">
  <div class='true'>seat {{ column_row }}</div>
</script>

app/views/flights/new.html.erb
<h1 class="burning">New flight</h1><hr>

<%= render 'form' %>

<%= link_to 'Back', flights_path %>

app/views/flights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Flight no:</strong>
  <%= @flights.flight_no %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @flights.origin %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @flights.destination %>
</p>

<p>
  <strong>Date:</strong>
  <%= @flights.date %>
</p>

<p>
  <strong>Airplane ID:</strong>
  <%= @flights.airplane_id %>
</p>

<%= link_to 'Edit', edit_flight_path(@flights) %> |
<%= link_to 'Back', flights_path %>