config/routes.rb
BurningAirline::Application.routes.draw do
  get "home/index"
  devise_for :users

  root :to => 'flights#landing'
  resources :airplanes
  resources :flights
  resources :reservations
  resources :seats
end

app/models/airplane.rb
# == Schema Information
#
# Table name: airplanes
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  row        :string(255)
#  column     :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Airplane < ActiveRecord::Base

  attr_accessible :name, :row, :column
  
  has_many :flights
end

app/controllers/airplanes_controller.rb
class AirplanesController < ApplicationController
  before_action :set_airplane, only: [:show, :edit, :update, :destroy]

  before_filter :check_if_admin

  # GET /airplanes
  # GET /airplanes.json
  def index
    @airplanes = Airplane.all
  end

  # GET /airplanes/1
  # GET /airplanes/1.json
  def show
  end

  # GET /airplanes/new
  def new
    @airplane = Airplane.new
  end

  # GET /airplanes/1/edit
  def edit
  end

  # POST /airplanes
  # POST /airplanes.json
  def create
    @airplane = Airplane.new(airplane_params)
    
    respond_to do |format|
      if @airplane.save
        format.html { redirect_to @airplane, notice: 'Airplane was successfully created.' }
        format.json { render action: 'show', status: :created, location: @airplane }
      else
        format.html { render action: 'new' }
        format.json { render json: @airplane.errors, status: :unprocessable_entity }
      end
    end

    # rows_array = (1..@airplane.row.to_i).to_a
    # column_array = (1..@airplane.column.to_i).to_a
    

    # rows_array.each do |row_name|
    #   column_array.each do |column_name|
    #     seat_name = row_name.to_s + "-" + column_name.to_s 
    #     seat = Seat.create(:column_row => seat_name, :flight_id => @airplane.id, :available => true)
    #   end
    # end

    
  end

  # PATCH/PUT /airplanes/1
  # PATCH/PUT /airplanes/1.json
  def update
    respond_to do |format|
      if @airplane.update(airplane_params)
        format.html { redirect_to @airplane, notice: 'Airplane was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @airplane.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /airplanes/1
  # DELETE /airplanes/1.json
  def destroy
    @airplane.destroy
    respond_to do |format|
      format.html { redirect_to airplanes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_airplane
      @airplane = Airplane.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def airplane_params
      params.require(:airplane).permit(:name, :row, :column)
    end

    def check_if_admin
      redirect_to(root_path) if current_user.nil? || current_user.admin == false
    end
end

app/helpers/airplanes_helper.rb
module AirplanesHelper
end

app/views/airplanes/_form.html.erb
<%= form_for(@airplane) do |f| %>
  <% if @airplane.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@airplane.errors.count, "error") %> prohibited this airplane from being saved:</h2>

      <ul>
      <% @airplane.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, :class => 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :row %><br>
    <%= f.text_field :row, :class => 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :column %><br>
    <%= f.text_field :column, :class => 'form-control' %>
  </div>
  <div class="actions">
    <br><%= f.submit "Create Airplane", :class => 'btn btn-success' %>
  </div>
<% end %>

app/views/airplanes/edit.html.erb
<h1>Editing airplane</h1>

<%= render 'form' %>

<%= link_to 'Show', @airplane %> |
<%= link_to 'Back', airplanes_path %>

app/views/airplanes/index.html.erb
<h1>Listing airplanes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Row</th>
      <th>Column</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @airplanes.each do |airplane| %>
      <tr>
        <td><%= airplane.name %></td>
        <td><%= airplane.row %></td>
        <td><%= airplane.column %></td>
        <td><%= link_to 'Show', airplane %></td>
        <td><%= link_to 'Edit', edit_airplane_path(airplane) %></td>
        <td><%= link_to 'Destroy', airplane, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Airplane', new_airplane_path %>

app/views/airplanes/new.html.erb
<h1 class="burning">New airplane</h1><hr>

<%= render 'form' %>

<%= link_to 'Back', airplanes_path %>

app/views/airplanes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @airplane.name %>
</p>

<p>
  <strong>Row:</strong>
  <%= @airplane.row %>
</p>

<p>
  <strong>Column:</strong>
  <%= @airplane.column %>
</p>

<%= link_to 'Edit', edit_airplane_path(@airplane) %> |
<%= link_to 'Back', airplanes_path %>